"""
Q) Each person's rank is given, smaller rank defeats the higher rank. 2 players are playing in one match. 
Display the matches being played. 

Example -

For input this - [5 3 1 8 4 6 2 7]
Output –
5 3 1 8 4 6 2 7
3 1 4 2
1 2
1

Note : This will only work if total matches are in power of '2'. 

Time Complexity: O(N). Although it looks like nested loops, the total number of matches played in a tournament is N - 1.
Space Complexity: O(N) to store the rounds, or O(1) if you modify the list in place (though O(N) is safer for clarity).
"""

def simulate_tournament(ranks):
    # Thought: Continue until only one winner remains
    while len(ranks) >= 1:
        # Step 1: Display current round participants
        print(*(ranks))
        
        # Termination: If we just printed the final winner, stop
        if len(ranks) == 1:
            break
            
        next_round = []
        # Step 2: Pair up adjacent players (0&1, 2&3, etc.)
        for i in range(0, len(ranks), 2):
            player1 = ranks[i]
            player2 = ranks[i+1]
            
            # Logic: Smaller rank defeats higher rank
            winner = min(player1, player2)
            next_round.append(winner)
        
        # Step 3: Update ranks for the next round iteration
        ranks = next_round

# Follow ups
"""
Q) "What if the input is 10^9 players? You can't store them all in memory. How would you find the winner if the ranks were generated by a stream?"
Ans : We can use a Stack-based Tournament. We don't need to know the billionth player to start playing the matches for the first two.
Note : 'player stream' means player is coming one by one. Players walk through the gate one by one. 
Once a player passes you, you can't "look back" at the ones who came before unless you specifically saved them in your memory (like a stack).

Logic: 
In a tournament, a player only moves up a level after winning a match. We can represent this using a Stack where each entry is a tuple: (rank, level).
    Level 0: A player who hasn't played any matches. (new player)
    Level 1: A player who won 1 match (defeated 2^1 total people).
    Level 2: A player who won 2 matches (defeated 2^2 total people).
The Golden Rule: When the player at the top of the stack has the same level as the incoming winner, they must play each other immediately.
The winner advances to level + 1.

A tournament is essentially a Perfect Binary Tree. 
By using a Stack, we can build this tree bottom-up. We only store a player if they are waiting for an opponent of the same level.

This is similar to how a Merge Sort or Segment Tree is built."

When you have 10^9 players, an O(N) space complexity (storing the whole list) will crash your system.
By using a Stack, we can find the winner using only O(log N) space. For 1 billion players, log_2(10^9) ~ 30. You only need to store 30 players in memory at any given time.

Time : O(N) , every player is kept one time in stack.
Space : O(logN) , At any given moment, the stack will never have more than one player per level. 
If two players were at the same level, they would have already played a match and merged into a single player at a higher level.
"""
def find_stream_winner(player_stream):
    # Each stack element is a tuple: (rank, level)
    stack = []
    
    for rank in player_stream:
        # 1. New player arrives as a Level 0 winner
        current = (rank, 0)
        
        # 2. Check if they can play a match immediately
        # Match happens if the top of the stack is at the SAME level
        while stack and stack[-1][1] == current[1]:
            opponent_rank, level = stack.pop()
            
            # Logic: Smaller rank defeats higher rank
            winner_rank = min(opponent_rank, current[0])
            
            # 3. Winner advances to the next level
            current = (winner_rank, level + 1)
            
        # 4. No more matches possible? Push the winner to wait
        stack.append(current)
    
    # --- Post-Stream Cleanup ---
    # If the total number of players wasn't a perfect power of 2, 
    # we might have multiple "island" winners at different levels.
    # We force them to play until only one is left.
    while len(stack) > 1:
        p1 = stack.pop()
        p2 = stack.pop()
        stack.append((min(p1[0], p2[0]), max(p1[1], p2[1]) + 1))
        
    return stack[0][0]
# Example Trace: [5, 3, 1, 8]
# 1. Receive 5: Stack [(5, 0)]
# 2. Receive 3: Level 0 matches! min(5, 3)=3. Stack [(3, 1)]
# 3. Receive 1: Stack [(3, 1), (1, 0)]
# 4. Receive 8: Level 0 matches! min(1, 8)=1. 
#    Now Level 1 matches! min(3, 1)=1. Stack [(1, 2)]
